export const ActionTypes = {
    FETCH_DATA_START: 'FETCH_DATA_START',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
    
    FILTER_DATA_BY_PRICE: 'FILTER_DATA_BY_PRICE',
    FILTER_DATA_BY_CATEGORY: 'FILTER_DATA_BY_CATEGORY'
}